[package]
name = "randprog_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["constructor", "display"] }
rand = "0.9.1"
strum = "0.27.2"
strum_macros = "0.27.2"
